// Canonical browser script load order for the editable canvas webview.
//
// The order is behavior-critical: helper modules attach namespaced browser
// APIs to window, then canvas.js wires them together and owns acquireVsCodeApi().
export const CANVAS_SCRIPT_FILES = [
  'canvas-geom.js',
  'canvas-controls.js',
  'canvas-context-toolbar-state.js',
  'canvas-context-toolbar.js',
  'canvas-menu.js',
  'canvas-context-menu.js',
  'canvas-insert-menu.js',
  'canvas-end-insert.js',
  'canvas-images.js',
  'canvas-icons.js',
  'canvas-text-metrics.js',
  'canvas-editing-utils.js',
  'canvas-editing-paste.js',
  'canvas-editing-keys.js',
  'canvas-editing.js',
  'canvas-chrome.js',
  'canvas-zoom.js',
  'canvas-spellcheck.js',
  'canvas-shortcut-help.js',
  'canvas-autoformat.js',
  'canvas-slash-menu.js',
  'canvas-keyboard-select.js',
  'canvas-move-block.js',
  'canvas-lint-marks.js',
  'canvas-find-replace.js',
  'canvas-keyboard-nav.js',
  'canvas-command-format.js',
  'canvas-command-shortcuts.js',
  'canvas-command-insert.js',
  'canvas-command-structure.js',
  'canvas-command-bar-ui.js',
  'canvas-command-bar.js',
  'canvas-properties.js',
  'canvas-styles.js',
  'canvas-table-resize.js',
  'canvas-table-hover.js',
  'canvas-table-insert-plus.js',
  'canvas-image-bar.js',
  'canvas-selection.js',
  'canvas-selection-aria.js',
  'canvas-selection-announce.js',
  'canvas-selection-summary.js',
  'canvas-selection-range.js',
  'canvas-selection-clipboard.js',
  'canvas-selection-restore.js',
  'canvas-selection-dependencies.js',
  'canvas-selection-controller.js',
  'canvas.js',
] as const;

export type CanvasScriptFile = typeof CANVAS_SCRIPT_FILES[number];
